# Add labels to PRs based on file changes

cli:
  - packages/eversession/**/*

studio:
  - packages/studio/**/*

changesets:
  - .changeset/**/*

ci:
  - .github/**/*

dependencies:
  - package.json
  - pnpm-lock.yaml
  - packages/**/package.json

documentation:
  - README.md
  - packages/**/README.md
  - "**/*.md"

